// Code generated by protoc-gen-go.
// source: slave_message.proto
// DO NOT EDIT!

/*
Package message is a generated protocol buffer package.

It is generated from these files:
	slave_message.proto
	slave_reply.proto

It has these top-level messages:
	SlaveMessage
*/
package message

import proto "code.google.com/p/goprotobuf/proto"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = math.Inf

type SlaveMessage struct {
	Msg              *string `protobuf:"bytes,1,req,name=msg" json:"msg,omitempty"`
	Reply            *string `protobuf:"bytes,2,opt,name=reply" json:"reply,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *SlaveMessage) Reset()         { *m = SlaveMessage{} }
func (m *SlaveMessage) String() string { return proto.CompactTextString(m) }
func (*SlaveMessage) ProtoMessage()    {}

func (m *SlaveMessage) GetMsg() string {
	if m != nil && m.Msg != nil {
		return *m.Msg
	}
	return ""
}

func (m *SlaveMessage) GetReply() string {
	if m != nil && m.Reply != nil {
		return *m.Reply
	}
	return ""
}

func init() {
}
