#!/bin/bash

echo "Hello"

export GOROOT=/usr/local/go
export PATH=$GOROOT/bin:$PATH

export GOPATH=$PWD/gopath
export PATH=$GOPATH/bin:$PATH

cd $(dirname $0)/..

#apt-get -y install strace

cd cs
go install .
cs